Repository KiaraL2/KnockKnock, pull requests merged in 2024-05, with the labels that each got.

#1 feat: 지원파트 마크업
  knockknock/src/main/webapp/adoptComplete.jsp
  knockknock/src/main/webapp/assets/CSS/Style.css
  knockknock/src/main/webapp/custMypage.jsp
  knockknock/src/main/webapp/header.html
  knockknock/src/main/webapp/images/favicon.ico
  knockknock/src/main/webapp/images/logo.png
  knockknock/src/main/webapp/pay.jsp
  knockknock/src/main/webapp/proposalComplete.jsp
  knockknock/src/main/webapp/purchaseDetail.jsp
  knockknock/src/main/webapp/requestComlpete.jsp
  knockknock/src/main/webapp/requestShow.jsp
  knockknock/src/main/webapp/requestWrite.jsp
  knockknock/src/main/webapp/review.jsp
  knockknock/src/main/webapp/sellerMypage.jsp
Labels: 🎨 Html&css

#3 fix:마크업 css, image 경로 수정
  knockknock/src/main/webapp/WEB-INF/web.xml
  knockknock/src/main/webapp/adoptComplete.jsp
  knockknock/src/main/webapp/custMypage.jsp
  knockknock/src/main/webapp/images/adopt.png
  knockknock/src/main/webapp/images/complete.png
  knockknock/src/main/webapp/main.jsp
  knockknock/src/main/webapp/pay.jsp
  knockknock/src/main/webapp/proposalComplete.jsp
  knockknock/src/main/webapp/purchaseDetail.jsp
  knockknock/src/main/webapp/requestComlpete.jsp
  knockknock/src/main/webapp/requestShow.jsp
  knockknock/src/main/webapp/requestWrite.jsp
  knockknock/src/main/webapp/review.jsp
  knockknock/src/main/webapp/sellerMypage.jsp
Labels: 🎨 Html&css

#5 feat: join 미완성
  knockknock/src/main/java/com/smhrd/controller/JoinController.java
  knockknock/src/main/java/com/smhrd/controller/MemberController.java
  knockknock/src/main/java/com/smhrd/db/mybatis-config.xml
  knockknock/src/main/java/com/smhrd/mapper/MemberMapper.xml
  knockknock/src/main/java/com/smhrd/model/CustomerDTO.java
  knockknock/src/main/java/com/smhrd/model/MemberDAO.java
  knockknock/src/main/java/com/smhrd/model/SellerDTO.java
  knockknock/src/main/webapp/WEB-INF/web.xml
  knockknock/src/main/webapp/join.jsp
Labels: ✨ Feature

#4 feat: proposalWrite 마크업 추가
  knockknock/src/main/webapp/proposalWrite.jsp
Labels: 🎨 Html&css

#7 feat: join 추가
  knockknock/src/main/java/com/smhrd/controller/JoinController.java
  knockknock/src/main/java/com/smhrd/mapper/MemberMapper.xml
  knockknock/src/main/java/com/smhrd/model/CustomerDTO.java
  knockknock/src/main/java/com/smhrd/model/MemberDAO.java
  knockknock/src/main/java/com/smhrd/model/SellerDTO.java
  knockknock/src/main/webapp/WEB-INF/web.xml
  knockknock/src/main/webapp/adoptComplete.jsp
  knockknock/src/main/webapp/assets/css/style.css
  knockknock/src/main/webapp/assets/js/join.js
  knockknock/src/main/webapp/custMypage.jsp
  knockknock/src/main/webapp/join.jsp
Labels: ✨ Feature, 🐞 BugFix

#8 feat: login 추가
  knockknock/src/main/java/com/smhrd/controller/LoginController.java
  knockknock/src/main/java/com/smhrd/mapper/MemberMapper.xml
  knockknock/src/main/java/com/smhrd/model/CustomerDTO.java
  knockknock/src/main/java/com/smhrd/model/MemberDAO.java
  knockknock/src/main/java/com/smhrd/model/SellerDTO.java
  knockknock/src/main/webapp/login.jsp
Labels: ✨ Feature

#9 feat: proposalWrite 작업중
  knockknock/src/main/java/com/smhrd/controller/ProposalController.java
  knockknock/src/main/java/com/smhrd/db/mybatis-config.xml
  knockknock/src/main/java/com/smhrd/mapper/ProposalMapper.xml
  knockknock/src/main/java/com/smhrd/model/ProposalDAO.java
  knockknock/src/main/java/com/smhrd/model/ProposalDTO.java
  knockknock/src/main/java/com/smhrd/model/RequestDTO.java
  knockknock/src/main/webapp/WEB-INF/web.xml
  knockknock/src/main/webapp/customerProfileEdit.jsp
  knockknock/src/main/webapp/main.jsp
  knockknock/src/main/webapp/proposalWrite.jsp
  knockknock/src/main/webapp/sellerProfileEdit.jsp
Labels: ✨ Feature

#10 feat: reviewWrite 구현중
  knockknock/src/main/java/com/smhrd/controller/ReviewWriteController.java
  knockknock/src/main/java/com/smhrd/mapper/ReviewMapper.xml
  knockknock/src/main/java/com/smhrd/model/ReviewDAO.java
  knockknock/src/main/java/com/smhrd/model/ReviewDTO.java
  knockknock/src/main/webapp/WEB-INF/web.xml
  knockknock/src/main/webapp/adoptComplete.jsp
  knockknock/src/main/webapp/customerProfileEdit.jsp
  knockknock/src/main/webapp/pay.jsp
  knockknock/src/main/webapp/proposalComplete.jsp
  knockknock/src/main/webapp/proposalShow.jsp
  knockknock/src/main/webapp/proposalWrite.jsp
  knockknock/src/main/webapp/purchaseDetail.jsp
  knockknock/src/main/webapp/requestComlpete.jsp
  knockknock/src/main/webapp/requestShow.jsp
  knockknock/src/main/webapp/requestWrite.jsp
  knockknock/src/main/webapp/review.jsp
Labels: ✨ Feature

#11 chore:merge conflict 수정
  knockknock/src/main/webapp/WEB-INF/web.xml
  knockknock/src/main/webapp/proposalWrite.jsp
Labels: 🐞 BugFix

#12 feat:custMypage 미완성
  knockknock/src/main/java/com/smhrd/controller/CustMypageController.java
  knockknock/src/main/java/com/smhrd/controller/LoginController.java
  knockknock/src/main/java/com/smhrd/controller/LogoutController.java
  knockknock/src/main/java/com/smhrd/db/db.properties
  knockknock/src/main/java/com/smhrd/db/mybatis-config.xml
  knockknock/src/main/java/com/smhrd/mapper/MemberMapper.xml
  knockknock/src/main/java/com/smhrd/mapper/RequestMapper.xml
  knockknock/src/main/java/com/smhrd/model/RequestDAO.java
  knockknock/src/main/java/com/smhrd/model/RequestDTO.java
  knockknock/src/main/webapp/WEB-INF/web.xml
  knockknock/src/main/webapp/custMypage.jsp
  knockknock/src/main/webapp/customerProfileEdit.jsp
  knockknock/src/main/webapp/header.html
  knockknock/src/main/webapp/header.jsp
  knockknock/src/main/webapp/images/SellerDefaultImg.jpg
  knockknock/src/main/webapp/images/generalDefaultImg.png
Labels: ✨ Feature

#14 feat:판매자 추천 알고리즘 적용
  knockknock/src/main/java/com/smhrd/controller/LoginController.java
  knockknock/src/main/java/com/smhrd/mapper/RequestMapper.xml
  knockknock/src/main/java/com/smhrd/model/RequestDAO.java
  knockknock/src/main/webapp/main.jsp
Labels: ✨ Feature

#16 chore:css전체 수정
  knockknock/src/main/webapp/adoptComplete.jsp
  knockknock/src/main/webapp/assets/css/style.css
  knockknock/src/main/webapp/assets/js/header.js
  knockknock/src/main/webapp/assets/js/portfolio.js
  knockknock/src/main/webapp/assets/js/ratingValue.js
  knockknock/src/main/webapp/assets/js/textExpand.js
  knockknock/src/main/webapp/assets/js/totalPrice.js
  knockknock/src/main/webapp/assets/js/userEdit.js
  knockknock/src/main/webapp/custMypage.jsp
  knockknock/src/main/webapp/customerProfileEdit.jsp
  knockknock/src/main/webapp/header.jsp
  knockknock/src/main/webapp/idFind.jsp
  knockknock/src/main/webapp/join.jsp
  knockknock/src/main/webapp/login.jsp
  knockknock/src/main/webapp/main.jsp
  knockknock/src/main/webapp/pay.jsp
  knockknock/src/main/webapp/proposalComplete.jsp
  knockknock/src/main/webapp/proposalShow.jsp
  knockknock/src/main/webapp/proposalWrite.jsp
  knockknock/src/main/webapp/purchaseDetail.jsp
  knockknock/src/main/webapp/requestComlpete.jsp
  knockknock/src/main/webapp/requestShow.jsp
  knockknock/src/main/webapp/requestWrite.jsp
  knockknock/src/main/webapp/review.jsp
  knockknock/src/main/webapp/sellerMypage.jsp
  knockknock/src/main/webapp/sellerProfileEdit.jsp
  knockknock/src/main/webapp/seller_profile.jsp
Labels: 🎨 Html&css

#17 fix: 누락된 admin 코드 추가
  knockknock/src/main/webapp/assets/js/header.js
  knockknock/src/main/webapp/login.jsp
Labels: 🎨 Html&css
